# Generated by Django 4.1.3 on 2022-11-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_final_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
