# Generated by Django 4.1.3 on 2022-11-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='visible_in_checkout',
        ),
    ]
