# Generated by Django 4.1.3 on 2022-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_discount_visible_in_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.IntegerField(),
        ),
    ]
