# Generated by Django 4.1.3 on 2022-11-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_discount_percent_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
    ]
