# Generated by Django 4.1.3 on 2022-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_discount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
