# Generated by Django 4.1.3 on 2022-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_discount_active_discount_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='visible',
        ),
    ]
