# Generated by Django 4.1.3 on 2022-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_discount_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
