# Generated by Django 4.1.3 on 2022-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_discount_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(default='Automatically assigned', max_length=55),
        ),
    ]
